name: RST2HTML
on:
  push:
    branches:
    - '**'
    - '!main'

jobs:
  if_merged:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'auto rebuilding site')"
    steps:
    - name: Deploy Configuration
      run: |
          mkdir ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.MY_ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
    - name: Checkout
      run: |
          env
          git clone git@github.com:${GITHUB_REPOSITORY}.git src -b main

    - name: Merge ${{ github.ref_name }} to main
      env:
        GITHUB_USER: "builduser"
        GITHUB_EMAIL: "test-builduser@example.com"
      run: |
          cd src
          git merge -m "auto merge" origin/${{ github.ref_name }}

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
          cd src
          python -m pip install --upgrade pip
          pip install -r documentation/requirements.txt
    - name: Build
      run: |
          cd src/documentation
          make html
    - name: Push
      env:
        GITHUB_USER: "builduser"
        GITHUB_EMAIL: "test-builduser@example.com"
      run: |
          cd src
          git config --local user.name "${GITHUB_USER}"
          git config --local user.email "${GITHUB_EMAIL}"
          git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
          git add -f documentation/html
          git commit -m "auto rebuilding site"
          git push origin main